# 应用服务 WEB 访问端口
server:
  port: 8100

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Jwt中cliam的iss属性，也就是jwt签发地址，即认证服务器的根路径
          # 资源服务器会进一步的配置，通过该地址获取公钥以解析jwt
          issuer-uri: http://127.0.0.1:8080


